This will be my rough book where I get to test things out before building it into a pipeline.

In [30]:
from sqlalchemy import create_engine
import pandas as pd
import os
from dotenv import load_dotenv
from datetime import datetime, timedelta

pd.set_option('display.max_columns', None)

load_dotenv()

True

In [31]:
DB_NAME = os.getenv('DB_NAME')
DB_USER = os.getenv('DB_USER')
DB_PASSWORD = os.getenv('DB_PASSWORD')
DB_HOST = os.getenv('DB_HOST')
DB_PORT = os.getenv('DB_PORT')

DB_URL = f'postgresql://{DB_USER}:{DB_PASSWORD}@{DB_HOST}:{DB_PORT}/{DB_NAME}'

conn = create_engine(DB_URL)

In [32]:
print(conn)

Engine(postgresql://postgres:***@analytics-psudo-webstore.c3eok0uoe3r2.eu-west-1.rds.amazonaws.com:5432/postgres)

In [36]:
users = pd.read_sql('select * from users', conn)
txn = pd.read_sql('select * from transactions', conn)

print(users.columns.tolist())
print(txn.columns.tolist())

['user_id', 'first_name', 'last_name', 'email', 'country', 'plan', 'account_status', 'created_at', 'kyc_verified', 'device_type']
['transaction_id', 'sender_id', 'receiver_id', 'currency', 'amount', 'currency_rate', 'transaction_status', 'transaction_type', 'transaction_date', 'converted_amount']

In [40]:
print(users.shape[0])
print(txn.shape[0])

1800
10000

In [ ]:
print(users['created_at'].dtype)
print(users['created_at'].head())

datetime64[us]
0   2022-04-03
1   2021-03-07
2   2024-08-23
3   2025-04-04
4   2022-11-21
Name: created_at, dtype: datetime64[us]

In [41]:
users['created_at'] = pd.to_datetime(users['created_at'])

In [42]:
# Extracting cohort period (month and year) from created_at
users['cohort_period'] = users['created_at'].dt.to_period('M')
users.head(10)

,user_id,first_name,last_name,email,country,plan,account_status,created_at,kyc_verified,device_type,cohort_period
0,b63b0d91-7080-4ea0-a371-321e7b39e631,Alan,Watts,wilcoxmelissa@example.net,Canada,basic,active,2022-04-03,True,iOS,2022-04
1,40e2aa13-ddcc-470a-9549-fab738ee6566,Adriana,Hernandez,barbarafoley@example.com,Nigeria,standard,active,2021-03-07,True,iOS,2021-03
2,792b22fe-89be-4e9c-bae6-d118220d7696,Krista,West,johnchase@example.net,Spain,basic,active,2024-08-23,False,iOS,2024-08
3,f703e64a-2fe3-442f-92ff-a184e7333030,Andrew,Moore,josephellis@example.com,Italy,basic,churned,2025-04-04,False,Android,2025-04
4,17a73f44-5eb3-4f43-b814-52b820d0787c,Alexander,Mcclain,williamslori@example.com,Germany,basic,suspended,2022-11-21,True,iOS,2022-11
5,ad3da735-5599-4f9f-8724-0eab42bbcefb,Charles,Hamilton,tcarlson@example.net,Germany,basic,active,2021-03-30,False,Android,2021-03
6,7c371406-fa43-47c0-92ca-6deb73d26576,Kimberly,Bennett,wheelerryan@example.org,Portugal,basic,active,2025-08-26,False,Web,2025-08
7,8d6e447e-7b6a-4d55-a971-51a62e4b2e2a,Kenneth,Miller,palmerjulie@example.com,France,basic,active,2024-09-16,True,iOS,2024-09
8,14039923-e528-42b2-aeae-ba5f715c20ba,Lacey,Graham,michael15@example.net,USA,basic,active,2022-07-24,True,Web,2022-07
9,3aed86ad-9a05-414a-921b-d2d5375962c0,Ryan,Church,reneedavid@example.com,USA,basic,active,2024-12-08,False,Android,2024-12

In [46]:
txn

,transaction_id,sender_id,receiver_id,currency,amount,currency_rate,transaction_status,transaction_type,transaction_date,converted_amount
0,2fe5432d-1f87-4ea7-aef5-e7d25259b7a2,7c829cb7-5996-4404-abd8-88cd253061f3,a9e59ed1-84de-46c8-87a5-89c643c1750a,GBP,1416.57,1.270,completed,receive,2025-07-27,1799.0439
1,1839fab2-1ce7-4d58-81fb-dc4a8ca03c91,b1690b71-111f-4902-b20e-95ce1233dbf7,7c829cb7-5996-4404-abd8-88cd253061f3,INR,4990.45,0.012,completed,receive,2025-04-08,59.8854
2,caf478ad-7717-4e75-94c9-bba09b680670,ca024e34-5e37-47d1-a64e-0c8ee6f93921,915c0a6d-e278-4390-a00b-775f4a8edcbb,EUR,616.27,1.080,status unknown,send,2024-06-05,665.5716
3,6e7f3f59-181a-4a34-bcff-a82fa95f61e7,3239a8ab-f3ad-496f-a861-a10db60c2ba5,79f51dcc-ef96-41a7-a33c-2eabb8fd3644,EUR,1033.28,1.080,completed,deposit,2025-04-20,1115.9424
4,089887a9-37f3-44d1-9ff1-e6878be27262,eed089ba-118d-4d3b-ba02-1c2ab5e136b1,478c8411-52b7-4726-beb0-891e3b01be26,USD,2220.49,1.000,completed,receive,2025-09-01,2220.4900
...,...,...,...,...,...,...,...,...,...,...
9995,c0ec785f-309f-4d40-b9ca-2ba7ec603278,fe92c2d2-17c1-404a-8fdf-e8f0de5ea82c,040b6164-d336-47ff-9584-314f5543f2da,CAD,423.71,0.740,completed,send,2024-12-17,313.5454
9996,b086d763-a04a-4298-a0b2-c99343409428,2e63dafb-bba2-48c4-97f7-11ea238590fe,e8c5f0cd-47ee-4e55-b455-d958445dfef4,BRL,2694.89,0.200,status unknown,withdrawal,2025-03-24,538.9780
9997,12d025e5-df9e-47a8-a6cc-d5d8896d28cc,921d077d-a39e-4cc3-bd82-26a9e4e208c2,fab638aa-019c-4fab-a820-85e36d03516b,EUR,2168.93,1.080,completed,receive,2024-11-04,2342.4444
9998,f3ba6214-6e44-425d-9039-6d6e7828cb8a,19dce850-9a68-4a52-a781-3a32f189ab52,8ec06cde-b22f-4b71-8ef7-9558555b2ab4,EUR,3931.32,1.080,completed,deposit,2022-09-05,4245.8256
9999,c50e8d0a-3488-41ba-9d77-79d8eeb8d89f,91a0d977-f861-4e84-bb2c-dc55e462708f,74b7019b-74c8-4b9f-b3d8-63508ab325b9,INR,2155.15,0.012,failed,send,2025-10-01,25.8618

In [ ]:
# Merge both tables so we have all we need in one dataframe
# we only need the user_id, cohort month and then the date of activity 
new_df = pd.merge(users[['user_id', 'cohort_period']], txn[['transaction_date']], left_on='user_id', right_on='sender_id', how='left')

KeyError: 'sender_id'

In [52]:
new_df

                                    user_id cohort_period transaction_date
0      b63b0d91-7080-4ea0-a371-321e7b39e631       2022-04       2022-09-20
1      b63b0d91-7080-4ea0-a371-321e7b39e631       2022-04       2022-11-06
2      b63b0d91-7080-4ea0-a371-321e7b39e631       2022-04       2024-06-25
3      b63b0d91-7080-4ea0-a371-321e7b39e631       2022-04       2022-05-27
4      b63b0d91-7080-4ea0-a371-321e7b39e631       2022-04       2024-08-14
...                                     ...           ...              ...
10001  f7ee076a-aa55-4df8-9731-915a700c738b       2021-06       2025-03-01
10002  f7ee076a-aa55-4df8-9731-915a700c738b       2021-06       2023-11-22
10003  f7ee076a-aa55-4df8-9731-915a700c738b       2021-06       2025-07-01
10004  f7ee076a-aa55-4df8-9731-915a700c738b       2021-06       2025-04-30
10005  f7ee076a-aa55-4df8-9731-915a700c738b       2021-06       2023-01-21

[10006 rows x 3 columns]